# Generated by Django 2.2.4 on 2019-08-20 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('open_arm_length', models.FloatField()),
                ('close_arm_length', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('entrances_close_right', models.IntegerField()),
                ('entrances_close_left', models.IntegerField()),
                ('entrances_open_right', models.IntegerField()),
                ('entrances_open_left', models.IntegerField()),
                ('time_close_right', models.FloatField()),
                ('time_close_left', models.FloatField()),
                ('time_open_right', models.FloatField()),
                ('time_open_left', models.FloatField()),
                ('time_moving', models.FloatField()),
                ('time_idle', models.FloatField()),
                ('max_speed', models.FloatField()),
                ('min_speed', models.FloatField()),
                ('maze', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mouse_tracker.Maze')),
            ],
        ),
    ]
