# Generated by Django 2.2.4 on 2019-08-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouse_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='datetime',
            new_name='datetime_start',
        ),
        migrations.RemoveField(
            model_name='test',
            name='time_close_left',
        ),
        migrations.RemoveField(
            model_name='test',
            name='time_close_right',
        ),
        migrations.RemoveField(
            model_name='test',
            name='time_open_left',
        ),
        migrations.RemoveField(
            model_name='test',
            name='time_open_right',
        ),
        migrations.AddField(
            model_name='test',
            name='datetime_end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='timein_close_left',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='test',
            name='timein_close_right',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='test',
            name='timein_open_left',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='test',
            name='timein_open_right',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='maze',
            name='close_arm_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='maze',
            name='open_arm_length',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='entrances_close_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='entrances_close_right',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='entrances_open_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='entrances_open_right',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='max_speed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='test',
            name='min_speed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_idle',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='test',
            name='time_moving',
            field=models.FloatField(default=0.0),
        ),
    ]
