# Generated by Django 2.2.4 on 2019-08-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouse_tracker', '0002_auto_20190820_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('CM', 'Camundongo'), ('RT', 'Rato')], default='RT', max_length=10)),
                ('nickname', models.CharField(max_length=100)),
                ('code_number', models.IntegerField(unique=True)),
            ],
        ),
    ]
