# Generated by Django 2.2.4 on 2019-08-21 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mouse_tracker', '0003_animal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
