# Generated by Django 2.2.4 on 2019-10-19 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mouse_tracker', '0005_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='MazeAreaSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initX', models.IntegerField(default=0)),
                ('initY', models.IntegerField(default=0)),
                ('areaW', models.IntegerField(default=0)),
                ('areaH', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='cruzamentos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='timein_close',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='test',
            name='timein_open',
            field=models.FloatField(default=0.0),
        ),
    ]
